// <auto-generated />
using System;
using LifetimeToolManage.Model.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LifetimeToolManage.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251116111905_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("LifetimeToolManage.Model.DB.ActiveTool", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ToolId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ToolId");

                    b.ToTable("ActiveTool");
                });

            modelBuilder.Entity("LifetimeToolManage.Model.DB.Lifetime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ToolId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("quantity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("registerTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ToolId");

                    b.ToTable("Lifetimes");
                });

            modelBuilder.Entity("LifetimeToolManage.Model.DB.Tools", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tools");
                });

            modelBuilder.Entity("LifetimeToolManage.Model.DB.ActiveTool", b =>
                {
                    b.HasOne("LifetimeToolManage.Model.DB.Tools", "Tool")
                        .WithMany()
                        .HasForeignKey("ToolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tool");
                });

            modelBuilder.Entity("LifetimeToolManage.Model.DB.Lifetime", b =>
                {
                    b.HasOne("LifetimeToolManage.Model.DB.Tools", "Tool")
                        .WithMany("Lifetime")
                        .HasForeignKey("ToolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tool");
                });

            modelBuilder.Entity("LifetimeToolManage.Model.DB.Tools", b =>
                {
                    b.Navigation("Lifetime");
                });
#pragma warning restore 612, 618
        }
    }
}
